name: mosaic_cloud
description: A Flutter widget that displays a collection of widgets in a mosaic or orthogonal word cloud layout.
version: 0.2.1
homepage: https://github.com/alex-marochko/mosaic_cloud

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  # This package supports all platforms.
